# Generated by Django 5.0.4 on 2024-05-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recp_name', models.CharField(max_length=100)),
                ('recp_desp', models.TextField()),
                ('recp_img', models.ImageField(upload_to='recipe_img')),
            ],
        ),
    ]
