# Generated by Django 5.0.4 on 2024-05-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veges', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
