# Generated by Django 5.0.4 on 2024-05-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veges', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_img/default_profile_img.png', null=True, upload_to='profile_img'),
        ),
    ]
